version: "3.8"
 
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile-test
    links:
    - openid-connect-provider-debugger
  openid-connect-provider-debugger:
    build:
      context: .
      dockerfile: Dockerfile
