FROM alpine:latest

# hadolint ignore=DL3018
RUN apk update \
 && apk --no-cache add curl \
 && rm -rf /var/cache/apk/*

CMD ["/usr/bin/curl", "-i", "-s", "-S", "-f", "http://openid-connect-provider-debugger"]
