FROM alpine:3.22.2@sha256:265b17e252b9ba4c7b7cf5d5d1042ed537edf6bf16b66130d93864509ca5277f

HEALTHCHECK NONE

ENTRYPOINT []

ARG USER_NAME=default
ARG USER_HOME=/home/default
ARG USER_ID=1000
ARG USER_GECOS=Default

SHELL ["/bin/ash", "-euo", "pipefail", "-c"]

# hadolint ignore=DL3018 # [Pin versions in apk add]: not required for testing
RUN apk add --no-cache curl

RUN adduser \
  --home "${USER_HOME}" \
  --uid "${USER_ID}" \
  --gecos "${USER_GECOS}" \
  --disabled-password \
  "${USER_NAME}"

ENV HOME="${USER_HOME}"

USER "${USER_NAME}"

WORKDIR "${HOME}"

# sleep 60s to make sure that container survived its own healthcheck
CMD ["/bin/ash", "-euo", "pipefail", "-c", "/bin/sleep 60 ; /usr/bin/curl -ifsSL http://openid-connect-provider-debugger"]
