name: Docker

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: openid-connect-provider-debugger
      run: |
        docker-compose --file docker-compose.test.yml build
        docker-compose --file docker-compose.test.yml run sut
