---
name: Docker

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: openid-connect-provider-debugger
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          sbom: true
          tags: leplusorg/csv:latest
      - name: Test the Docker image
        working-directory: openid-connect-provider-debugger
        run: docker compose -f docker-compose.test.yml run sut
