name: Docker

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    # run only on internal PRs, external ones already run on push.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: openid-connect-provider-debugger
      run: |
        docker-compose --file docker-compose.test.yml build
        docker-compose --file docker-compose.test.yml run sut
