---
name: Luarocks Check Versions

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

defaults:
  run:
    working-directory: openid-connect-provider-debugger

jobs:
  luarocks-check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Check outdated dependencies
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          rc=0
          \sudo apt install -y luarocks
          while IFS=' ' read -r package current_version ; do
            latest_version="$(\luarocks search "${package}" --porcelain | \awk -F'\t' -v pkg="${package}" '$1 == pkg {print $2}' | \sort -Vr | \head -n 1)"
            if [ "${current_version}" != "${latest_version}" ]; then
              echo "${package} ${current_version} -> ${latest_version}"
              rc=$((rc+1))
            fi
          done < <(\lua -e 'local t = dofile("luarocks.lock"); for package, version in pairs(t.dependencies) do print(package .. " " .. version) end')
          exit ${rc}
